export const EDIT_TASK = 'tasks/taskEdit'
export const CREATE_TASK = 'tasks/taskAdded'
export const DELETE_TASK = 'tasks/taskDelete'
export const FILTERED_TASKS = 'tasks/tasksFilter'
export const COMPLETED_TASK = 'tasks/taskCompleted'